name: terraform-plan

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  first-job:
    runs-on: ubuntu-latest

    env:
      working-directory: example/parent-module

    steps:
      - name: Clone repo inside runner
        uses: actions/checkout@v6

      - name: Check Azure client secret
        shell: bash
        run: |
          if [ -z "${{ secrets.AZURE_CLIENT_SECRET }}" ]; then
            echo "AZURE_CLIENT_SECRET is EMPTY or NOT AVAILABLE"
            exit 1
          else
            echo "AZURE_CLIENT_SECRET is available"
          fi

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Verify Terraform installation
        run: terraform --version

      - name: Terraform init
        working-directory: ${{ env.working-directory }}
        run: terraform init

      - name: Terraform Validation check
        working-directory: ${{ env.working-directory }}
        run: terraform validate

      - name: Terraform Plan initiation
        working-directory: ${{ env.working-directory }}
        run: terraform plan -no-color